/* tslint:disable */
/* eslint-disable */
/**
 * RC中国-爱宠有卡
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CustomerAddress
 */
export interface CustomerAddress {
    receiver: string;
    phone: string;
    country: string;
    province: string;
    city: string;
    region: string;
    detail: string;
    postcode: string;
    isDefault: boolean;
    id: string;
}


