/* tslint:disable */
/* eslint-disable */
/**
 * RC中国-爱宠有卡
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CustomerAddress,
    OrderBuyer,
    OrderLineItem,
    OrderPayInfo,
    OrderShippingInfo,
    OrderTradePrice,
    OrderTradeState,
} from './';

/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    _id: string;
    version: string;
    orderNumber: string;
    currencyCode: string;
    remark: string;
    isSubscription: boolean;
    buyer: OrderBuyer;
    shippingAddress: CustomerAddress;
    shippingInfo: OrderShippingInfo;
    tradePrice: OrderTradePrice;
    tradeState: OrderTradeState;
    payInfo: OrderPayInfo;
    lineItem: Array<OrderLineItem>;
    timeStamp: number;
}


