/* tslint:disable */
/* eslint-disable */
/**
 * RC中国-爱宠有卡
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface OrderLineItem
 */
export interface OrderLineItem {
    oid: string;
    spuId: string;
    spuNo: string;
    spuName: string;
    skuId: string;
    skuNo: string;
    skuName: string;
    pic: string;
    num: string;
    description: string;
    price: string;
    discountsPrice: string;
    goodsSpecifications: string;
    bundle: boolean;
}


