/* tslint:disable */
/* eslint-disable */
/**
 * RC中国-爱宠有卡
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    OrderTradeStateCreatedby,
} from './';

/**
 * 
 * @export
 * @interface OrderTradeState
 */
export interface OrderTradeState {
    orderState: OrderTradeStateOrderStateEnum;
    createdAt: string;
    createdby: OrderTradeStateCreatedby;
    lastModifiedAt: string;
    lastModifiedBy: OrderTradeStateCreatedby;
    orderType: string;
    storeId: string;
}

/**
* @export
* @enum {string}
*/
export enum OrderTradeStateOrderStateEnum {
    Unpaid = 'Unpaid',
    ToShip = 'To ship',
    Shipped = 'Shipped',
    Completed = 'Completed'
}


