/* tslint:disable */
/* eslint-disable */
/**
 * RC中国-爱宠有卡
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProductVariantType {
    RealProductInfo = 'RealProductInfo',
    ViturlProductInfo = 'ViturlProductInfo',
    BundleProductInfo = 'BundleProductInfo',
    VetProductInfo = 'VetProductInfo',
    GiftProductInfo = 'GiftProductInfo'
}

export function ProductVariantTypeFromJSON(json: any): ProductVariantType {
    return ProductVariantTypeFromJSONTyped(json, false);
}

export function ProductVariantTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVariantType {
    return json as ProductVariantType;
}

export function ProductVariantTypeToJSON(value?: ProductVariantType | null): any {
    return value as any;
}

