/* tslint:disable */
/* eslint-disable */
/**
 * RC中国-爱宠有卡
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Product,
    ProductAssets,
    ProductVariantSubcription,
    ProductVariantType,
} from './';

/**
 * 
 * @export
 * @interface ProductVariant
 */
export interface ProductVariant {
    id: string;
    pruduct: Product;
    skuNo: string;
    spuSkuNo: string;
    eanCode: string;
    name: string;
    productInfoType: ProductVariantType;
    marketingPrice: string;
    listPrice: string;
    costPrice: string;
    isShelves: string;
    shelvesTime: string;
    store: string;
    weight: string;
    unitUom: string;
    infoUnit: string;
    defaultImage: string;
    productVariantSubscription: ProductVariantSubcription;
    feedingDays: string;
    images: Array<ProductAssets>;
}


