/* tslint:disable */
/* eslint-disable */
/**
 * RC中国-爱宠有卡
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductAssets
 */
export interface ProductAssets {
    id: string;
    product_id: string;
    product_varient_id: string;
    artwork_url: string;
    middle_url: string;
    thumb_url: string;
    big_url: string;
    image_type: string;
    video_url: string;
    video_type: string;
    assers_rank: string;
    created_at: string;
    default_image: string;
    created_by: string;
    last_modified_at: string;
    last_modified_by: string;
}


