/* tslint:disable */
/* eslint-disable */
/**
 * RC中国-爱宠有卡
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BrandInfo,
    ProductAssets,
    ProductSpecifiction,
    ProductType,
    ProductVariant,
    StoreAccount,
} from './';

/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    id: string;
    key: string;
    version: string;
    createdAt: Date;
    createdBy: StoreAccount;
    lastModifiedAt: string;
    lastModifiedBy: StoreAccount;
    spuNo: string;
    name: string;
    cardName: string;
    unit: string;
    description: string;
    listPrice: string;
    marketingPrice: string;
    isSupport100: string;
    type: ProductType;
    brandId: BrandInfo;
    isShelves: boolean;
    specifictionId: ProductSpecifiction;
    defaultImage: ProductAssets;
    salesStatus: boolean;
    skus: Array<ProductVariant>;
    isEnableVarients: boolean;
    isDisplay: boolean;
}


