/* tslint:disable */
/* eslint-disable */
/**
 * RC中国-爱宠有卡
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ShipmentState {
    NotShipped = 'NotShipped',
    AllShipped = 'AllShipped',
    Received = 'Received'
}

export function ShipmentStateFromJSON(json: any): ShipmentState {
    return ShipmentStateFromJSONTyped(json, false);
}

export function ShipmentStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipmentState {
    return json as ShipmentState;
}

export function ShipmentStateToJSON(value?: ShipmentState | null): any {
    return value as any;
}

